# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    name: "Continuous Integration"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Typecheck"
        run: npm run typecheck

      - name: "Lint"
        run: npm run lint
